/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 12-20-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class Client {
    Public String name = 'David';
    Public Integer age = '39';
    public void clientDataaMethod(){

        String ageToText = String.valueOf(age);
        System.debug('The name of the client is' + name);
    }
    }

